# 01 - Data Loading (Gene Expression + miRNA Expression)

This notebook loads transcriptomic datasets from GEO (GSE53482),
including both gene expression (GEP) and miRNA expression (miEP) profiles.

The data is derived from CD34+ cells of PMF patients and healthy controls.

Steps:
- Load GEO series matrix files (gene + miRNA)
- Extract expression tables
- Clean and format data (remove quotes, set indices, convert to numeric)
- Transpose data (samples as rows, features as columns)
- Save processed datasets for downstream analysis

### Import Custom Data Processing Functions

In [ ]:
# Loading Required Libraries
import sys
import os

sys.path.append(os.path.abspath(".."))

# Import custom functions for data loading and preprocessing
from Src.Data_Preprocessing import load_geo_matrix, clean_expression_data

### Define Data File Paths

Specify the file paths for the raw GEO datasets:
- Gene expression (GEP)
- miRNA expression (miEP)

In [15]:
# File paths for raw GEO datasets
gene_file = "..\Data\Raw\GSE53482-GPL13667_series_matrix.txt.gz"
mirna_file = "..\Data\Raw\GSE53482-GPL14613_series_matrix.txt.gz"

### Load Gene Expression Data

Load the gene expression dataset from the GEO series matrix file.

In [16]:
# Load raw gene expression data
gene_df = load_geo_matrix(gene_file)

# Check dimensions (rows = probes, columns = samples)
gene_df.shape

(49386, 74)

In [17]:
# Preview raw gene expression data
gene_df.head()

,"""ID_REF""","""GSM1294472""","""GSM1294473""","""GSM1294474""","""GSM1294475""","""GSM1294476""","""GSM1294477""","""GSM1294478""","""GSM1294479""","""GSM1294480""",...,"""GSM1294631""","""GSM1294632""","""GSM1294633""","""GSM1294634""","""GSM1294635""","""GSM1294636""","""GSM1294637""","""GSM1294638""","""GSM1294639""","""GSM1294640"""
0,"""11715100_at""",3.44781,3.53247,3.4817,3.75482,3.70343,3.70231,3.57824,3.41587,3.3393,...,3.56223,3.40801,3.4347,3.42855,3.67426,3.70755,3.64355,3.50871,3.73836,3.62929
1,"""11715101_s_at""",5.55402,5.62314,5.31757,5.67073,5.81079,5.53288,5.46934,5.20784,5.20912,...,5.43214,5.71271,5.55509,5.43214,5.51451,5.39289,5.51859,5.49293,5.15963,5.47905
2,"""11715102_x_at""",3.7472,3.7182,3.66868,3.77408,4.1881,3.70022,3.51492,3.77682,3.69956,...,3.7182,3.65248,3.71211,3.68301,3.95926,3.70599,3.79657,3.80876,3.65757,3.69948
3,"""11715103_x_at""",4.59447,4.4895,4.35037,4.39825,4.64891,4.74673,4.43852,4.28628,4.23457,...,4.76271,4.47891,4.73332,4.0943,4.27587,4.69806,4.1541,4.38573,4.27452,4.76797
4,"""11715104_s_at""",3.6829,3.5962,3.59208,3.65722,3.7562,3.91177,3.92554,3.57535,3.66221,...,3.61751,3.58392,3.42584,3.63008,3.69687,4.11056,4.01461,3.67472,3.49618,3.81639

### Clean and Transform Gene Expression Data

Apply preprocessing steps to convert the raw Gene Expression data into an ML-ready format.

This includes:
- Removing formatting artifacts (quotation marks)
- Setting probe IDs as index
- Converting values to numeric
- Transposing the matrix

In [18]:
# Clean and transform gene expression data
gene_df = clean_expression_data(gene_df)

# Check new shape (rows = samples, columns = genes)
gene_df.shape

(73, 49386)

In [19]:
# Preview transformed gene expression data
print("Gene expression shape:", gene_df.shape)

Gene expression shape: (73, 49386)

### Verify Gene Expression Dataset Dimensions

Confirm the number of samples and features after preprocessing.

In [20]:
# Display number of samples and genes
print("Samples:", gene_df.shape[0])
print("Genes:", gene_df.shape[1])

Samples: 73
Genes: 49386

### Load miRNA Expression Data

Load the miRNA expression dataset from the GEO series matrix file.

In [21]:
# Load raw miRNA expression data
mirna_df = load_geo_matrix(mirna_file)

# Check dimensions (rows = probes, columns = samples)
mirna_df.shape

(20212, 74)

In [22]:
# Preview raw miRNA expression data
mirna_df.head()

,"""ID_REF""","""GSM1294399""","""GSM1294400""","""GSM1294401""","""GSM1294402""","""GSM1294403""","""GSM1294404""","""GSM1294405""","""GSM1294406""","""GSM1294407""",...,"""GSM1294462""","""GSM1294463""","""GSM1294464""","""GSM1294465""","""GSM1294466""","""GSM1294467""","""GSM1294468""","""GSM1294469""","""GSM1294470""","""GSM1294471"""
0,"""14q0_st""",1.57253,1.39147,1.16992,0.938129,1.30996,1.29011,1.3992,1.22555,1.12978,...,1.09156,0.776448,0.954856,0.680954,0.805272,1.19954,0.913693,0.806013,0.932633,0.851082
1,"""14qI-1_st""",1.37446,1.42942,0.866827,1.95183,1.59601,1.40776,1.3992,1.02175,1.65865,...,1.46384,1.12155,1.98037,1.46281,1.25735,1.55599,1.31976,0.984278,1.15048,1.26778
2,"""14qI-1_x_st""",1.79616,1.82932,1.61705,1.65853,1.47324,1.32836,1.51397,2.25726,1.36249,...,1.59434,1.28365,2.14116,1.35988,1.93627,1.57643,1.61705,1.13144,0.986304,1.67775
3,"""14qI-2_st""",0.848568,0.748387,0.572901,0.674714,0.505116,0.506277,0.570887,0.750935,0.60093,...,1.16198,0.973073,0.760069,0.955913,0.846695,0.738519,0.723147,1.01462,0.758366,1.08184
4,"""14qI-3_x_st""",1.51213,1.0845,1.26616,1.07057,0.627153,0.737875,1.67231,0.785656,1.06575,...,0.733337,1.12407,0.799456,0.998525,0.835925,0.701533,0.871436,0.737089,0.900816,0.94573

### Clean and Transform miRNA Expression Data

Apply preprocessing steps to convert the raw miRNA Expression data into an ML-ready format. (Follow same steps as for the Gene Expression dataset)

In [23]:
# Clean and transform miRNA expression data
mirna_df = clean_expression_data(mirna_df)

# Check new shape (rows = samples, columns = genes)
mirna_df.shape

(73, 20212)

In [24]:
# Preview transformed gene expression data
mirna_df.head()

ID_REF,14q0_st,14qI-1_st,14qI-1_x_st,14qI-2_st,14qI-3_x_st,14qI-4_st,14qI-4_x_st,14qI-5_st,14qI-6_st,14qI-6_x_st,...,zma-miR482-star_st,zma-miR482_st,zma-miR528a-star_st,zma-miR528a_st,zma-miR528b-star_st,zma-miR528b_st,zma-miR529-star_st,zma-miR529_st,zma-miR827-star_st,zma-miR827_st
GSM1294399,1.572530,1.374460,1.79616,0.848568,1.512130,3.363630,1.564220,1.237070,1.584650,0.748334,...,0.705208,0.725911,0.868092,1.281160,1.218240,1.107110,0.477373,1.123400,0.929993,0.838821
GSM1294400,1.391470,1.429420,1.82932,0.748387,1.084500,2.608190,1.593630,2.303580,0.722771,1.378250,...,1.108030,0.928884,2.359200,1.990090,2.076180,1.542640,1.001290,0.711792,0.915731,0.831021
GSM1294401,1.169920,0.866827,1.61705,0.572901,1.266160,0.932293,0.804126,0.629725,0.689443,0.708159,...,0.601052,0.801090,1.180150,0.964182,0.748193,1.582890,1.582890,0.991561,0.934935,0.728468
GSM1294402,0.938129,1.951830,1.65853,0.674714,1.070570,0.801090,1.163750,0.508694,1.088380,1.200820,...,1.369210,0.875938,0.674714,1.116040,0.569810,0.988569,0.754800,0.642420,1.109100,1.187640
GSM1294403,1.309960,1.596010,1.47324,0.505116,0.627153,3.142920,2.639960,0.999244,1.424460,1.998630,...,0.751484,0.665127,0.944978,0.730955,1.393110,0.744246,0.625288,1.155950,0.527479,0.861172

### Verify miRNA Expression Dataset Dimensions

Confirm the number of samples and features after preprocessing.

In [25]:
# Display number of samples and miRNAs
print("Samples:", mirna_df.shape[0])
print("miRNAs:", mirna_df.shape[1])

Samples: 73
miRNAs: 20212

### Save Processed Data

Save cleaned datasets for reuse in downstream analysis notebooks.

In [26]:
# Create processed directory if it doesn't exist
os.makedirs("../Data/Processed", exist_ok=True)

# Save processed data
gene_df.to_csv("../Data/Processed/gene_expression.csv")
mirna_df.to_csv("../Data/Processed/mirna_expression.csv")