# 02 - Metadata Processing & Label Construction

This notebook processes sample metadata from GEO (GSE53482)
and constructs labels for downstream machine learning tasks.

Key steps:
- Load processed gene expression data
- Extract sample metadata from GEO series matrix file
- Parse metadata into structured format
- Construct classification labels (PMF vs Control)
- Align metadata with expression dataset
- Validate dataset integrity
- Save processed metadata

In [58]:
# Loading Required Libraries
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath(".."))

# Import custom functions for data loading and preprocessing
from Src.Data_Preprocessing import extract_metadata, parse_metadata

In [59]:
gene_file = "../Data/Raw/GSE53482-GPL13667_series_matrix.txt.gz"

In [60]:
meta_gene_raw = extract_metadata(gene_file)
meta_gene_clean = parse_metadata(meta_gene_raw)

meta_gene_clean.head()

             supplier cell type disease jak2v617f tissue
GSM1294472  Vannucchi       MPD     PMF       neg     PB
GSM1294473  Vannucchi       MPD     PMF       pos     PB
GSM1294474  Vannucchi       MPD     PMF       pos     PB
GSM1294475  Vannucchi       MPD     PMF       pos     PB
GSM1294476  Vannucchi       MPD     PMF       pos     PB

In [61]:
meta_gene_clean["disease"].value_counts()

disease
PMF       42
PB CTR    16
BM CTR    15
Name: count, dtype: int64

In [62]:
meta_gene_clean["label"] = meta_gene_clean["disease"].map({
    "PMF": 1,
    "PB CTR": 0,
    "BM CTR": 0
})

meta_gene_clean["label"].value_counts()

label
1    42
0    31
Name: count, dtype: int64

In [63]:
meta_gene_clean.index = meta_gene_clean.index.str.replace('"', '')

In [64]:
gene_df = pd.read_csv("../Data/Processed/gene_expression.csv", index_col=0)

In [65]:
gene_df = gene_df.loc[meta_gene_clean.index]
assert gene_df.index.equals(meta_gene_clean.index)

In [66]:
gene_df.to_csv("../Data/Processed/gene_expression_aligned.csv")
meta_gene_clean.to_csv("../Data/Processed/meta_gene_data.csv")

In [67]:
mirna_file = "../Data/Raw/GSE53482-GPL14613_series_matrix.txt.gz"

In [68]:
meta_mirna_raw = extract_metadata(mirna_file)
meta_mirna_clean = parse_metadata(meta_mirna_raw)

meta_mirna_clean.head()

             supplier cell type disease jak2v617f tissue
GSM1294399  Vannucchi       MPD     PMF       pos     PB
GSM1294400  Vannucchi       MPD     PMF       neg     PB
GSM1294401  Vannucchi       MPD     PMF       pos     PB
GSM1294402  Vannucchi       MPD     PMF       pos     PB
GSM1294403  Vannucchi       MPD     PMF       neg     PB

In [69]:
meta_mirna_clean["disease"].value_counts()

disease
PMF       42
PB CTR    16
BM CTR    15
Name: count, dtype: int64

In [70]:
meta_mirna_clean["label"] = meta_mirna_clean["disease"].map({
    "PMF": 1,
    "PB CTR": 0,
    "BM CTR": 0
})

meta_mirna_clean["label"].value_counts()

label
1    42
0    31
Name: count, dtype: int64

In [71]:
meta_mirna_clean.index = meta_mirna_clean.index.str.replace('"', '')

In [72]:
mirna_df = pd.read_csv("../Data/Processed/mirna_expression.csv", index_col=0)

In [73]:
mirna_df = mirna_df.loc[meta_mirna_clean.index]
assert mirna_df.index.equals(meta_mirna_clean.index)

In [74]:
mirna_df.to_csv("../Data/Processed/mirna_expression_aligned.csv")
meta_mirna_clean.to_csv("../Data/Processed/meta_mirna_data.csv")