# 02 - Metadata Processing & Label Construction

This notebook processes sample metadata from GEO (GSE53482)
and constructs labels for downstream machine learning tasks.

Key steps:
- Load processed gene expression data
- Extract sample metadata from GEO series matrix file
- Parse metadata into structured format
- Construct classification labels (PMF vs Control)
- Align metadata with expression dataset
- Validate dataset integrity
- Save processed metadata

In [1]:
# Load required libraries
import pandas as pd
import sys
import os

# Add project root to system path for module imports
sys.path.append(os.path.abspath(".."))

# Import custom functions for metadata extraction and parsing
from Src.Data_Preprocessing import extract_metadata, parse_metadata

### Define Raw Data File Paths

Specify file paths for both the raw GEP and miEP GEO series matrix files for metadata extraction and downstream processing

In [2]:
# File path for raw gene expression GEO series matrix
gene_file = "../Data/Raw/GSE53482-GPL13667_series_matrix.txt.gz"

# File path for raw miRNA expression GEO series matrix
mirna_file = "../Data/Raw/GSE53482-GPL14613_series_matrix.txt.gz"

### Load Processed Expression Datasets

Load cleaned gene expression and miRNA datasets for alignment with metadata.

In [3]:
# Load processed gene expression dataset
gene_df = pd.read_csv("../Data/Processed/gene_expression.csv", index_col=0)

# Load processed miRNA expression dataset
mirna_df = pd.read_csv("../Data/Processed/mirna_expression.csv", index_col=0)

### Extract and Parse Gene Expression Metadata

In [4]:
# Extract raw metadata from gene expression file
meta_gene_raw = extract_metadata(gene_file)

# Parse and clean metadata into structured format
meta_gene_clean = parse_metadata(meta_gene_raw)

# Preview cleaned metadata
meta_gene_clean.head()

             supplier cell type disease jak2v617f tissue
GSM1294472  Vannucchi       MPD     PMF       neg     PB
GSM1294473  Vannucchi       MPD     PMF       pos     PB
GSM1294474  Vannucchi       MPD     PMF       pos     PB
GSM1294475  Vannucchi       MPD     PMF       pos     PB
GSM1294476  Vannucchi       MPD     PMF       pos     PB

### Inspect Disease Distribution (Gene)

Examine the distribution of disease categories in the gene metadata to validate class composition before label encoding.

In [5]:
# Check distribution of disease categories
meta_gene_clean["disease"].value_counts()

disease
PMF       42
PB CTR    16
BM CTR    15
Name: count, dtype: int64

### Create Binary Labels for Classification (Gene)

Convert disease categories into binary labels for supervised learning (PMF vs Control).

In [6]:
# Map disease categories to binary labels
meta_gene_clean["label"] = meta_gene_clean["disease"].map({
    "PMF": 1,
    "PB CTR": 0,
    "BM CTR": 0
})

# Verify label distribution
meta_gene_clean["label"].value_counts()

label
1    42
0    31
Name: count, dtype: int64

### Align Gene Expression Data with Metadata

Ensure that gene expression samples are aligned with the metadata by matching sample identifiers and verifying consistency.

In [7]:
# Align gene expression data to metadata sample order
gene_df = gene_df.loc[meta_gene_clean.index]

# Verify alignment between gene expression and metadata
assert gene_df.index.equals(meta_gene_clean.index)

### Save Processed and Aligned Datasets

Save the cleaned and aligned gene expression data and corresponding metadata for use in downstream analysis and modelling.

In [8]:
# Save aligned gene expression dataset
gene_df.to_csv("../Data/Processed/gene_expression_aligned.csv")

# Save cleaned and labeled metadata
meta_gene_clean.to_csv("../Data/Processed/meta_gene_data.csv")

### Extract and Parse miRNA Metadata

Extract metadata from the miRNA GEO series matrix file and parse it into a structured format for downstream analysis.

In [9]:
# Extract raw metadata from miRNA file
meta_mirna_raw = extract_metadata(mirna_file)

# Parse and clean metadata into structured format
meta_mirna_clean = parse_metadata(meta_mirna_raw)

# Preview cleaned metadata
meta_mirna_clean.head()

             supplier cell type disease jak2v617f tissue
GSM1294399  Vannucchi       MPD     PMF       pos     PB
GSM1294400  Vannucchi       MPD     PMF       neg     PB
GSM1294401  Vannucchi       MPD     PMF       pos     PB
GSM1294402  Vannucchi       MPD     PMF       pos     PB
GSM1294403  Vannucchi       MPD     PMF       neg     PB

### Inspect Disease Distribution (miRNA)

Examine the distribution of disease categories in the miRNA metadata to validate class composition before label encoding.

In [10]:
# Check distribution of disease categories
meta_mirna_clean["disease"].value_counts()

disease
PMF       42
PB CTR    16
BM CTR    15
Name: count, dtype: int64

### Create Binary Labels for Classification (miRNA)

Convert disease categories into binary labels for supervised learning (PMF vs Control).

In [11]:
# Map disease categories to binary labels
meta_mirna_clean["label"] = meta_mirna_clean["disease"].map({
    "PMF": 1,
    "PB CTR": 0,
    "BM CTR": 0
})

# Verify label distribution
meta_mirna_clean["label"].value_counts()

label
1    42
0    31
Name: count, dtype: int64

### Align miRNA Expression Data with Metadata

Ensure that miRNA expression samples are aligned with the metadata by matching sample identifiers and verifying consistency.

In [12]:
# Align miRNA expression data to metadata sample order
mirna_df = mirna_df.loc[meta_mirna_clean.index]

# Verify alignment between miRNA expression and metadata
assert mirna_df.index.equals(meta_mirna_clean.index)

### Save Processed and Aligned miRNA Datasets

Save the cleaned and aligned miRNA expression data and corresponding metadata for downstream analysis and modelling.

In [13]:
# Save aligned miRNA expression dataset
mirna_df.to_csv("../Data/Processed/mirna_expression_aligned.csv")

# Save cleaned and labeled metadata
meta_mirna_clean.to_csv("../Data/Processed/meta_mirna_data.csv")